config/routes.rb
Rails.application.routes.draw do

  resources :species do
      resources :sightings
    end
  #resources :sightings
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :species

  validates :date, :presence => true
  validates :longitude, :presence => true
  validates :latitude, :presence => true
  validates :species_id, :presence => true
end

app/models/species.rb
class Species < ActiveRecord::Base
  validates :name, :presence => true
  has_many :sightings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.all
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    species = Species.find(params[:species_id])
    @sighting = species.sightings.new
  end

  # GET /sightings/1/edit
  def edit
    @sighting = Sighting.find(params[:id])
    # format.html { render '/species/'+ @species.id.to_s + @sighting.id.to_s +'/edit' }
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @species = Species.find(params[:species_id])
    @sighting = Sighting.new(sighting_params)
    @sighting.species = @species

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to '/species/'+ @species.id.to_s, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    species = Species.find(params[:species_id])
    @sighting.species = @species
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to '/species/'+ @species.id.to_s, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @species = Species.find(params[:species_id])
    @sighting = Sighting.find(params[:id])
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to '/species/'+ @species.id.to_s, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :latitude, :longitude, :species_id)
    end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]

  # GET /species
  # GET /species.json
  def index
    @species = Species.all
  end

  # GET /species/1
  # GET /species/1.json
  def show
    @species = Species.find(params[:id])
    @sighting = Sighting.new
    @sighting.species = @species
    render('species/show.html.erb')
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species.destroy
    respond_to do |format|
      format.html { redirect_to species_index_url, notice: 'Species was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def species_params
      params.require(:species).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Speciestracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= form_for(@sighting, url: species_path(@species)+'/sightings') do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <!-- <div class="field">
    <%= f.label :species_id %><br>
    <%= f.number_field :species_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form' %>

app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sightings</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Species</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= sighting.species_id %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sighting', new_sighting_path %>

app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form' %>

<%= link_to 'Back', '/species' %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Species:</strong>
  <%= @sighting.species_id %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>

app/views/species/_form.html.erb
<%= form_for(@species) do |f| %>
  <% if @species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
      <% @species.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/species/edit.html.erb
<h1>Editing Species</h1>

<%= render 'form' %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

app/views/species/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Species</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @species.each do |species| %>
      <tr>
        <td><%= species.name %></td>
        <td><%= link_to 'Show', species %></td>
        <td><%= link_to 'Edit', edit_species_path(species) %></td>
        <td><%= link_to 'Destroy', species, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Species', new_species_path %>

app/views/species/new.html.erb
<h1>New Species</h1>

<%= render 'form' %>

<%= link_to 'Back', species_index_path %>

app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @species.name %>
</p>


  <%= render('sightings/form') %>

<p>Sightings:</p>

<ul>
  <% @species.sightings.each do |sighting| %>
  <li>
    <%= sighting.date %> |
    <%= sighting.longitude %> |
    <%= sighting.latitude %> |
    <a href="/species/<%= @species.id %>/sightings/<%= sighting.id %>/edit">Edit</a> |
    <a href="/species/<%= @species.id %>/sightings/<%= sighting.id %>"
      data-confirm="You sure?"
      data-method="delete"
      rel="nofollow">Delete</a>
    </li>
    <% end %>
</ul>

<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_index_path %>